version: '3.8'

services:
  gmail-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mcp-gmail:/gmail-server
    environment:
      - GMAIL_CREDENTIALS_PATH=/gmail-server/credentials.json
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mcp-gmail: